### ISSUE TITLE
nrthmk's scripts continue executing in nmkin_1

### ISSUE THREAD

**Issue by Tom-III** [q-gears/q-gears#129] opened 2015-05-15 10:49 UTC
After you play through nrthmk and go into nmkin_1 nrthmk's LUA script keeps executing and as a result when  you reach the end of nmkin_1 and pass through what you think is Gateway1 you activate nrthmk's Gateway1 which ends up taking you to md8_4 INSTEAD of elevtr1.  This is a critical bug and prevents progress past nmkin_1

A possible solution would be to make sure to halt all of a field's scripts after its unloaded.  So when you leave a field the code should kill anything executing from the previous field to make sure the new fields scripts get loaded into the memory.

Heres the first hint that the wrong scripts are executing: l_door is an entity in nrthmk and NOT in nmkin_1
![Wrong field](http://i.imgur.com/Dlwx5KI.png)

Now heres where you normally walk in and goto the elevator (elevtr1)
![Normally...](http://i.imgur.com/uFw0BFj.png)

But heres where you end up because you actually walk into nrthmk's Gateway1 and NOT nmkin_1's Gateway1
![Wrong field!!!](http://i.imgur.com/y1pYUkB.png)

**Comment by paulsapps** [comment] 2015-05-15 15:18
Duplicate of https://github.com/q-gears/q-gears/issues/124

**Closed by paulsapps** 2015-05-15 15:18 UTC
